Iter15
MWT-proger/shortener pull request #17
Opened 2023-08-07 12:28 UTC by MWT-proger

Доработал правки

2023-08-07 18:25 UTC, valentinsoe requested changes
Спасибо за исправления.
Предыдущий PR просил смерджить, чтобы diff для проверки был поменьше:)
Вроде замечания расписал по PRу.

2023-08-07 18:25 UTC, valentinsoe commented on configs/configs.go
> +	TokenExp  time.Duration
Я по какой-то причине не вижу предыдущие свои комментарии к PR.
Но JWT токен и кука могут быть вообще без времени жизни, можно не делать его 99 лет:)

2023-08-07 18:25 UTC, valentinsoe commented on internal/shortener/auth/auth.go
> +			UserID, _ = GetUserID(tokenString)
Оба вызова функции GetUserId игнорируют ошибку. Зачем ее тогда вообще возвращать?:)

2023-08-07 18:25 UTC, valentinsoe commented on internal/shortener/router/router.go
> +		// r.Use(auth.ValidAuthCookieMiddleware) Закоментировал, потому что тесты не хотят принимать 401 ошибку когда нет кук
1) Группы в таком виде можно объединить. Они вроде не отличаются.
2) Когда нет кук - не надо возвращать 401. 401 надо возвращать когда кука есть, но она невалидна:)

2023-08-07 18:25 UTC, valentinsoe commented on internal/shortener/router/router.go
> +		// r.Use(auth.ValidAuthCookieMiddleware) Закоментировал, потому что тесты не хотят принимать 401 ошибку когда нет кук
Нет куки - пришел новый пользователь
Плохая кука - что-то пошло не по плану

2023-08-07 18:25 UTC, valentinsoe commented on internal/shortener/handlers/handlers.go
> +	channels := fanOut(h.doneCh, inputCh)
Я не очень понял что имеется ввиду честно говоря. Зачем плодить такое количество каналов?:)
Когда я писал замечание в прошлый раз, имелось ввиду что просто запускать на каждый вызов отдельную горутину удаления не соответсвует заданию. Достаточно иметь 1 канал, в который складываются ссылки к удалению, а одна отдельная горутина в фоне их читает и удаляет.
Почему важно удаление в одной горутине? Потому что это делает доступ на модификацию(не добавление, а именно модификацию) к хранилищу фактически однопоточным. Что в случае нашего самодельного хранилища в памяти - хорошо.

FanOut часть реализовывать нет нужды, она у нас есть из коробки. Ведь для каждого http-запроса стандартный http-сервер создает свою горутину.

Надеюсь объяснил что я ожидаю увидеть и почему FanIn здесь полезен:)

2023-08-07 19:58 UTC, MWT-proger commented on configs/configs.go
> +	TokenExp  time.Duration
убрал)

2023-08-07 20:00 UTC, MWT-proger commented on internal/shortener/auth/auth.go
> +			UserID, _ = GetUserID(tokenString)
на будущее) 
убрал

2023-08-07 20:03 UTC, MWT-proger commented on internal/shortener/router/router.go
> +		// r.Use(auth.ValidAuthCookieMiddleware) Закоментировал, потому что тесты не хотят принимать 401 ошибку когда нет кук
Вот тут немного поспорю) 
![image](https://github.com/MWT-proger/shortener/assets/47903160/65c58465-ea78-4c28-8533-53d488ed86ab)

2023-08-07 20:03 UTC, MWT-proger commented on internal/shortener/router/router.go
> +		// r.Use(auth.ValidAuthCookieMiddleware) Закоментировал, потому что тесты не хотят принимать 401 ошибку когда нет кук
Это как я понял относится ко всему серверу

2023-08-07 20:06 UTC, MWT-proger commented on internal/shortener/handlers/handlers.go
> +	channels := fanOut(h.doneCh, inputCh)
Я просто не понимал зачем здесь FanIn)

2023-08-07 20:10 UTC, MWT-proger commented on internal/shortener/handlers/handlers.go
> +	channels := fanOut(h.doneCh, inputCh)
**`Достаточно иметь 1 канал, в который складываются ссылки к удалению, а одна отдельная горутина в фоне их читает и удаляет.`** С этим соглашусь, но я не вижу в этом fanIn 
так я сделал в предыдущем коммите перед отправкой, потом навалил вот этого всего лишнего))))

2023-08-07 20:16 UTC, MWT-proger commented on internal/shortener/handlers/handlers.go
> +	channels := fanOut(h.doneCh, inputCh)
вроде теперь так)

2023-08-07 20:18 UTC, MWT-proger commented on internal/shortener/router/router.go
> +		// r.Use(auth.ValidAuthCookieMiddleware) Закоментировал, потому что тесты не хотят принимать 401 ошибку когда нет кук
Но сделаю

2023-08-07 20:32 UTC, MWT-proger commented
Так, но теперь вроде всё)

2023-08-07 20:33 UTC, MWT-proger commented
Прошу прощение, то что перед последними двумя коммитами не смержил

2023-08-07 20:34 UTC, MWT-proger commented
а предыдущие комментарий тут 
в закрытом ПР 
https://github.com/MWT-proger/shortener/pull/16#issue-1831760692

2023-08-08 08:38 UTC, valentinsoe commented on internal/shortener/handlers/handlers.go
> +	channels := fanOut(h.doneCh, inputCh)
Что есть FanIn в двух словах для go - у нас из многих разных горутин создаются задания, которые обрабатывает одна горутина последовательно.
Что есть FanOut в двух словах - одна горутина создает много заданий, которые обрабатывают много горутин одновременно.

Много горутин создающих задания в нашем случае это запускаемые http-сервером обработчики запросов. Потенциально любое количество пользователей(и даже один и тот же пользователь) могут прислать любое количество запросов на удаление одновременно.
А обрабатываем мы их "в фоне" и одной горутиной последовательно.

Опять же надеюсь, что стало понятнее.

2023-08-08 08:40 UTC, valentinsoe approved these changes
Спасибо за исправления!
Написал объяснение про FanIn, рекомендую почитать.
Если все еще не очень понятно в чем он здесь заключается - приходи пофлудить в пачку  соответсвующий канал:)

2023-08-08 13:33 UTC, MWT-proger commented on internal/shortener/handlers/handlers.go
> +	channels := fanOut(h.doneCh, inputCh)
Да, теперь все понял, спасибо)

2023-08-08 13:34 UTC, merged