Iter5
MWT-proger/shortener pull request #5
Opened 2023-06-07 20:27 UTC by MWT-proger

2023-06-12 10:01 UTC, rktkov requested changes

2023-06-12 10:01 UTC, rktkov commented on internal/shortener/storage/storage.go
> +type OperationStorage interface {
Я бы назвал OperationStorager - так будет звучать по ГОшному.

2023-06-12 10:01 UTC, rktkov commented on internal/shortener/storage/storage.go
> +func InitJSONFile() {
Не стоит завершать выполнение приложение по причине ошибки в вспомогательной функции. Лучше вернуть ошибку, и пусть уже клиентский код принимает решение, что делать дальше.

2023-06-12 10:01 UTC, rktkov commented on internal/shortener/storage/storage.go
> +package storage
Выбрано очень багоопасный подход - один файл, который является точкой и чтения и записи, причем подразумевается некая "правилная" последовательность, когда должно происходить запись, а когда чтение. Основные баги начнут происходить, когда конкуретные операции с файлом будут выполнятся. Обычно в таких сценариях реализуют некий буфер в памяти, который периодически сливают в файл. Обеспечить и контролировать синхронность доступа к памяти своего приложения легче, чем к объекту ОС (в данном случае файлу). Стоит пересмотреть логику этого пакета.

2023-06-12 10:01 UTC, rktkov commented on internal/shortener/router/router.go
> +	"github.com/MWT-proger/shortener/internal/shortener/handlers"
В одном месте импорты структурированы, а тут - нет. Консистентность надо соблюдать.

2023-06-12 10:01 UTC, rktkov commented on internal/shortener/handlers/handlers.go
> +			log.Fatal(err)
Почему fatal - почему не вернуть InternalError? В целом плохая практика в разных местах своего кода, из разных компонентов завершать приложение. В идеале это должно быть одно место, расположенное где-то в районе запуска приложения.

2023-06-12 10:01 UTC, rktkov commented on internal/shortener/handlers/handlers.go
> +		log.Fatal(err)
см. комментарии

2023-06-12 10:01 UTC, rktkov commented on internal/shortener/handlers/handlers.go
> +	http.Error(res, "Bad Request", http.StatusBadRequest)
Я бы местами поменял логику. Вначале проверил все негативные случаи и вернул ошибку, а потом обрабатывал бы валидные ситуации. Читабельность кода улучшает. Вот ниже по коду так же сделано. Консистентность надо соблюдать.

2023-06-12 20:40 UTC, MWT-proger commented on internal/shortener/handlers/handlers.go
> +		log.Fatal(err)
согласен, эти фатылы вообще не к месту

2023-06-13 20:20 UTC, MWT-proger commented on internal/shortener/storage/storage.go
> +package storage
Да, согласен
Я это понимал, но так как будем все равно менять хранилище не стал сразу делать.
Сейчас сделал более безопасный метод по совету

2023-06-14 18:01 UTC, closed without merging